### ISSUE TITLE
No 2nd Popup Window

### ISSUE THREAD

**Issue by manicslothpdx** [homebysix/misc#4]
This script has been added to a policy in our JSS which is configured with a trigger of recurring check-in. On El Capitan, the first popup is displayed fine but the second popup that requests the password is never displayed. This happens on all of our El Capitan Macs. The logs are:

Script exit code: 239
Script result: Alerting user bmarks about incoming password prompt...
0Prompting bmarks for their Mac password...
Prompting bmarks for their Mac password (attempt 2)...
Prompting bmarks for their Mac password (attempt 3)...
Prompting bmarks for their Mac password (attempt 4)...
Prompting bmarks for their Mac password (attempt 5)...
[ERROR] Password prompt unsuccessful after 5 attempts.

**Comment by benmartel** [comment]
Looks like we are having the same issue. I am going to have to dig into it today.

**Comment by homebysix** [comment]
Thanks for reporting, @manicslothpdx. I've seen this before too, and I've been meaning to keep an issue open about it.

I've reviewed the code and didn't see anything obvious, but I'd be interested to hear what you find @benmartel.

**Comment by benmartel** [comment]
I still have not got a chance to dig into this. It is high on my priority list though.@homebysix I reviewed it too and could not find anything obvious.

**Comment by MScottBlake** [comment]
I'm not sure what's causing the original problem, but the return code of 239 is a result of "Out of range exit values can result in unexpected exit codes. An exit value greater than 255 returns an exit code modulo 256. For example, exit 3809 gives an exit code of 225 (3809 % 256 = 225)." (source: http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF)

I had the same problem the first time my test machine ran this script, but it has worked fine on subsequent times.

**Comment by benmartel** [comment]
I am going to finally have time to dig into this today. Will update you on what we find.

**Comment by MScottBlake** [comment]
Adding a "sleep 1" after the osascript commands seems to have fixed it for
me.

**Comment by manicslothpdx** [comment]
@MScottBlake I tried that and got an interesting result. The second popup was displayed, which was the first time that happened for me, but the text in the window implied an invalid password had been entered at least once, i.e. "Sorry, that password was incorrect. Please try again" instead of the "Please enter your password" as being the first text displayed in the 2nd popup.

**Comment by MScottBlake** [comment]
Touche.

I hadn't posted anything back here yet because I hadn't done any real testing past checking to see if the prompt appeared. Good catch.

**Comment by manicslothpdx** [comment]
I partially take back my previous comment from yesterday. I've only been able to replicate that behavior on one Mac. During all subsequent tests on other Macs, the originally reported issue still occurred.

**Comment by benmartel** [comment]
After doing some research I can confirm that the script runs when you manually call the policy by id or you call it from self service. If the Policy is called by recurring check in or login it seems to fail to interact with osascript properly. When it fails it does not seem to pass the password variable and just immediately say it is wrong. Don't know if that points people any closer but it seems to be a complex problem.

**Comment by benmartel** [comment]
Looks like we may have figured out what the problem was I updated the branch. https://github.com/homebysix/misc/pull/8

**Comment by homebysix** [comment]
OK, master branch has been updated with two pull requests. Thanks to @benmartel for the "run AppleScript as current user" idea.

Give it a try, and let me know here if you still see this issue. Thanks!
